import Head from 'next/head'

export default function About() {
  return (
    <>
      <Head>
        <title>About Me | Drew Cooper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full container mx-auto px-16">
        <h1 className="text-3xl text-center flex w-fit mx-auto py-4">
          About Me
        </h1>
        <div className="mx-auto flex flex-col w-1/2 py-4 space-y-8">
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima
            quaerat laborum blanditiis facere! Ex, nemo enim? Dolore odit quas
            sapiente quo ducimus voluptate nobis, molestias incidunt voluptates
            rerum assumenda illum.
          </p>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima
            quaerat laborum blanditiis facere! Ex, nemo enim? Dolore odit quas
            sapiente quo ducimus voluptate nobis, molestias incidunt voluptates
            rerum assumenda illum.
          </p>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima
            quaerat laborum blanditiis facere! Ex, nemo enim? Dolore odit quas
            sapiente quo ducimus voluptate nobis, molestias incidunt voluptates
            rerum assumenda illum.
          </p>
        </div>
      </main>
    </>
  )
}
