import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Drew Cooper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto h-full">
        <div className="w-full flex flex-col justify-center items-start h-[50vh] px-16">
          <h1 className="text-3xl">Hi, I'm Drew Cooper</h1>
          <h2 className="text-2xl">I build things for the web</h2>
          <p className="w-1/3">
            I'm a software engineer focusing primarily on full stack web
            development. Currently I am working on building both web & desktop
            applications for{' '}
            <a className="text-banana-mania-200" href="https://clockk.com">
              Clockk.com
            </a>
          </p>
        </div>
      </main>
    </>
  )
}
