import Head from 'next/head'
export default function Work() {
  return (
    <>
      <Head>
        <title>Work | Drew Cooper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full container mx-auto px-16">
        <h1 className="text-3xl text-center flex w-fit mx-auto py-4">Work</h1>
      </main>
    </>
  )
}
